### ISSUE TITLE
file-option: recursive for source files

### ISSUE THREAD

**Issue by AndreasAmMueller** [ygoe/DotnetMakeDeb#1]
It would be great to have the possibillity not only to copy the files within the source directory, but also the files in subdirectories.

This would make the package build of a ASP.NET Core application more easy as you'll have many folders within your `wwwroot`.

**Comment by ichan-akira** [comment]
Agreed, this feature will be proven useful.

**Comment by ichan-akira** [comment]
Thanks so much @ygoe I will try it out next week!

I am actively using your tool right now! 👍 👍 👍

**Comment by ichan-akira** [comment]
It work flawlessly, thanks!

**Comment by ygoe** [comment]
Thanks for the feedback, great to hear that!
