### ISSUE TITLE
FileName is too long. It must be less than 100 bytes

### ISSUE THREAD

**Issue by ichan-akira** [ygoe/DotnetMakeDeb#3]
Hi @ygoe I got following error:
```
Error: An unhandled exception has occurred: FileName is too long. It must be less than 100 bytes.
```

When trying to create Debian package with following `*.debspec`:
```
# Spec file options
basepath: .
outdir: .

# Common directory variables
APP_NAME = myapp

SETUP_DIR = Setup\Linux
INSTALLDIR = Files\INSTALLDIR
PROGRAMDATA_CONFIG_DIR = Files\PROGRAMDATA_CONFIG_DIR 

OPT_DIR = opt/{APP_NAME}
VAR_DIR = var/opt/{APP_NAME}

# Package control file
package: {APP_NAME}
version: 1.0.0.0
architecture: amd64
maintainer: John Doe <john.doe@email.com>
homepage: https://john.doe.com/
description: My App is created by John Doe.

# Maintenance scripts
preinst: {SETUP_DIR}\preinst text
postinst: {SETUP_DIR}\postinst text
prerm: {SETUP_DIR}\prerm text
postrm: {SETUP_DIR}\postrm text

# Startup scripts
file: {SETUP_DIR}\{APP_NAME} etc/init.d/ 755

# Application files
file: {INSTALLDIR}\** {OPT_DIR}/ 755

# Configuration
conffile: {INSTALLDIR}\Configuration\** {OPT_DIR}/Configuration/ 755
conffile: {PROGRAMDATA_CONFIG_DIR}\** {VAR_DIR}/ 755

# This line seems the one that causing trouble
file: {INSTALLDIR}\Configuration\** {OPT_DIR}/abcdefghijklmnopqrstuvwxyz/abcdefghijklmnopqrstuvwxyz/abcdefghijklmnopqrstuvwxyz/ 755
```

Do the target path have path+file name length limitation? How can we get around this issue, since from what I have look up following are the limitation in Linux (source: Ref: https://askubuntu.com/a/859953/937325):
> The max filename length is 255 bytes.
> And a maximum path of 4096 characters.

**Comment by ygoe** [comment]
I searched through the source code for this message. It's in TarHeader.cs line 161. Looks like it's a tar limitation. This is somewhat external code, I found it somewhere else (I hope it's noted somewhere). But if it needs to pad the field for 100 chars length, I guess it only has so much space. Nothing I or probably anyone else could change. Have you tried creating und reading a tar archive with such long file names? If that works, maybe there's a newer version of the tar format that this code doesn't know. But I don't know either, so somebody else would have to provide the necessary code change.

**Comment by ichan-akira** [comment]
> I searched through the source code for this message. It's in TarHeader.cs line 161. Looks like it's a tar limitation

I see, so it is from https://github.com/ygoe/DotnetMakeDeb/blob/a4fa9cc2ddb3cee4e2945ef2c89086812afc5a80/DotnetMakeDeb/Tar/TarHeader.cs#L161 (I haven't notice about it until now).

> But if it needs to pad the field for 100 chars length, I guess it only has so much space. Nothing I or probably anyone else could change. Have you tried creating und reading a tar archive with such long file names? If that works, maybe there's a newer version of the tar format that this code doesn't know. But I don't know either, so somebody else would have to provide the necessary code change.

Got it, I will check further is there anything I could find.
For now however, I'm using workaround which conform to the 100 bytes target path+file name limit when creating Debian package.

**Comment by ichan-akira** [comment]
Ah I see, it seems that this issue is very difficult to solve at this point of time, since yes it is limitation of how TAR archive is designed. I have check also the [Debian manual page for TAR](https://manpages.debian.org/testing/libarchive-dev/tar.5.en.html),  turns out the `name` in the struct is defined as follows:
```
char name[100];
```

Interestingly enough turns out in [POSIX ustar Archives](https://manpages.debian.org/testing/libarchive-dev/tar.5.en.html#POSIX_ustar_Archives) there is new variable:
```
char prefix[155];
```

which defined as:
> name, prefix
> If the pathname is too long to fit in the 100 bytes provided by the standard format, it can be split at any / character with the first portion going into the prefix field. If the prefix field is not empty, the reader will prepend the prefix value and a / character to the regular name field to obtain the full pathname. The standard does not require a trailing / character on directory names, though most implementations still include this for compatibility reasons.

And in other section it is also mentioned:

> The prefix field is often not used, limiting pathnames to the 100 characters of old-style archives.

Well that is my finding. Unfortunately I have not check for TAR implementation which harness the `prefix` variable.
