### ISSUE TITLE
conffile directive seems does not support text keyword

### ISSUE THREAD

**Issue by ichan-akira** [ygoe/DotnetMakeDeb#5]
I have tried your example at https://htmlpreview.github.io/?https://github.com/ygoe/DotnetMakeDeb/blob/master/MakeDeb.html or specifically at https://github.com/ygoe/DotnetMakeDeb/blob/9b71c28a58123b3f8d8ac839e91c49e0d40c7910/MakeDeb.html#L426
```
conffile: Setup\Config\Linux\myapp.cfg text    {ETCDIR}/
```

Running that example will give me:
```
Specification file: D:\Documents\Visual Studio\DotnetMakeDeb\Example\myapp.debspec
Error: An unhandled exception has occurred: Unrecognised directive in line 30.
Press any key to exit...
```

It seems `conffile` directive does not support `text` keyword?

**Comment by ygoe** [comment]
I'm using this directive in my own spec file, so I can't reproduce this.

**Comment by ichan-akira** [comment]
I think the problem is the `text` part is on the different index.

I mean, after I tinkering around with your code, turns out the `text` keyword does supported, it just the documentation seems have typo on it.

**Comment by ichan-akira** [comment]
I think documentation should write:
```
conffile: Setup\Config\Linux\myapp.cfg         {ETCDIR}/    text
```

instead of:
```
conffile: Setup\Config\Linux\myapp.cfg text    {ETCDIR}/
```

**Comment by ygoe** [comment]
Good catch, that was indeed in the wrong order in the example.
