### ISSUE TITLE
Extend the library

### ISSUE THREAD

**Issue by SuperJMN** [ygoe/DotnetMakeDeb#9]
Hi! I have discovered this project but it seems to cover only .deb files, (I know, that's the name of the project)

I wonder if you would like to cover more packaging formats for more OSes like Windows, Mac, Android...

I've found this project https://github.com/quamotion/dotnet-packaging, but it's not compatible with .NET 7+ and it seems unmaintained. I hope you can collaborate or create your own version.

Thanks!

**Comment by ygoe** [comment]
Sorry for the late reply. I don't plan to extend this tool to anything else beyond Debian packages. It's a specific use case and is targeted exactly towards it. Other package formats have completely other needs and most of the time also require different contents to be packaged. There will have to be separate tools for those workflows.

And finally, I only need (needed) to create Debian packages, so I made this tool. Windows has plenty of package formats and variants (and tools to use them), I have nothing to do with Apple stuff, and Android packages are already created by Visual Studio when using .NET MAUI.
